# Generated by Django 5.0.7 on 2025-10-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
